### ISSUE TITLE
CLI Configuartion

### ISSUE THREAD

**Issue by SuperMaZingCoder** [Shivansh-007/piston-cli#12]
## Description
Relevant to https://github.com/Shivansh-007/piston-cli/discussions/7#discussioncomment-373302. This allows configuration for the piston-cli such as theming, truncated line length, and more, which we can discuss in the issue.

## Reasoning
Currently, the theme must be passed at run time, and although we haven't implemented a max char flag yet, we will soon and that will also be passed at run time in piston-cli's current stage. With a configuration file, we can solve this by allowing users to define their favorite settings beforehand.

## Proposed Implementation
A YAML can be created in the user's OS' default configuration file location:
1. macOS/Unix: `~/.config/piston-cli/config.yaml`
2. Windows: `%APPDATA%/piston-cli/config.yaml`

which piston-cli will check for before each run, if no configuration file is found, defaults are used.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by Shivansh-007** [comment]
Sure! Assigned it to you!
