### ISSUE TITLE
Output is not correct

### ISSUE THREAD

**Issue by techguy940** [Shivansh-007/piston-cli#13]
## Description
Currently found for `print(input())`
Using `print(input())` will output the given input string in all lowercase not respecting the inputted string's case

## Steps to Reproduce
1. Write a simple function
Example: `def abc(): print(input())`
2. Call the function, `abc()`
3. Input stdin argument with some upper case letter, "Hello, world!"

## Expected Behaviour
It should print `Hello, world!`

## Actual Behaviour
It prints `hello, world!`
![image](https://user-images.githubusercontent.com/51826754/108162531-4fad3200-7113-11eb-9065-43260757d94e.png)

## Known Impacted Operating Systems
Currently tested on Windows 10

**Comment by Shivansh-007** [comment]
Tested locally the bug exists. Not sure why it is caused but will have a look!

Thanks for letting us know.

**Comment by Shivansh-007** [comment]
Found the problem.

![Screenshot from 2021-02-17 11-46-45](https://user-images.githubusercontent.com/69356296/108163956-e1b63a00-7115-11eb-9c2d-4c66b6c93ee9.png)

It is a problem with all the files, so wherever works on this, would need to change it on the files.
