### ISSUE TITLE
Implement the CLI with Click instead of argparse

### ISSUE THREAD

**Issue by Shivansh-007** [Shivansh-007/piston-cli#24]
## Description
Implement the command line interface (CLI) with the [Click library](https://click.palletsprojects.com/) instead of [argparse](https://docs.python.org/3/library/argparse.html).

## Reasoning
Using Click for the implementation of a CLI has numerous advantages over using argparse, including a more concise API, the enforcement of a more consistent interface, and built-in support for the implementation of test runners. In addition, the library comes with a collection of helper functions and tools, that are relevant for CLI development. It also provides autocomplete and can prompt for missing arguments. Please see [this page](https://click.palletsprojects.com/en/7.x/why/) for a more comprehensive overview of why one would want to implement a CLI with Click.

## Proposed Implementation
Make the changes in `__main__.py`, taking most advantage of the `click` library.

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by Kronifer** [comment]
I'd love to take this on, if thats ok

**Comment by Shivansh-007** [comment]
Thankyou for showing interest in this issue, but unfortunately this is still in planning state, I can get back to you once I discuss this further with super.

There are few other issues also open (including #55 since I haven't really started working on that).

**Comment by Shivansh-007** [comment]
Closed with #73
