### ISSUE TITLE
Piston-cli Load Time Issue

### ISSUE THREAD

**Issue by Darkship86** [Shivansh-007/piston-cli#40]
## Description
The piston-cli has a longer load time after installation and usage with exactly 5.3 secs load time...
this is a known issue and it would help to fix it.

## Proposed Implementation
My proposed implementation is to remove unused/additional modules on the code manually 

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [ x] Anyone can implement this feature

**Comment by Shivansh-007** [comment]
Thankyou for the issue, I would be working on this in the v3-piston-api branch.

**Comment by Shivansh-007** [comment]
This has hopefully been resolved in `v3-piston-api` branch, and will soon be in production in release 1.4.0 as soon as piston v3 gets launched.

All commands are launched within 2 seconds now.
