### ISSUE TITLE
Flesh out the readme 

### ISSUE THREAD

**Issue by Shivansh-007** [Shivansh-007/piston-cli#60]
It should probably have collapsible sections, maybe a table of contents, and screenshots of showcasing piston-cli

**Comment by franciscomgoliveira** [comment]
Hey, maybe I can do it... Pls send me only all the features and the content you want in the documentation. And the screenshots... Thx!

**Comment by Shivansh-007** [comment]
Hey @franciscomgoliveira thank you for showing interest in this.

I don't think there is a need to for someone to do the features/content of the documentation when I am sending everything, I could basically do that myself. Sorry if I am getting rude, don't know how else I can say it. I can provide the screenshots but the content itself should be done by the person who is assigned to this.

Content wise, here is a rough idea:

- How to write configuration and what all can be configured.
- All different `--list` commands
- All different execution commands i.e.
  * `--shell`
  * `--pastebin`
  * the default from input which is ran when you don't specify any flags
  * `--file`
- And a section for contributing to `piston-cli`, which I think I can do later.

**Comment by franciscomgoliveira** [comment]
Hey @Shivansh-007 
I did ask for the content only because I never used piston cli so I don't know exactly how it works. No problem, you were not rude 😉.

**Comment by Shivansh-007** [comment]
> Hey @Shivansh-007
> I did ask for the content only because I never used piston cli so I don't know exactly how it works. No problem, you were not rude wink.

Oh sure! After thinking about this, I think it would be better if this issue is left to the maintainers, since they are best familiar with the library and would be able to make the content most easily. You can checkout the other issues and comment if you are interested in them.

Thankyou, have a great day!
